import '../shared/justfile'

import './.dev/just/db.just'
import './.dev/just/composer.just'
import './.dev/just/tools.just'

env:
    @test -f .env || cp .env.example .env

init: env composer migrate seed

reinit: migrate-fresh seed

fix: pint-fix

lint: pint-lint
